[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

# Try using a simple redirect to the Python app
[[redirects]]
  from = "/*"
  to = "/wsgi.py"
  status = 200
